---
title: "Instructions for final report + presentation (Required)"

lastmod: 2018-12-30T00:00:00

draft: false
type: docs
maths: true	

output:
  blogdown::html_page:
    toc: true

linktitle: "Instructions (Required)"
menu:
   docs:
      parent: SOC224 Final Report
      weight: 10

---

# Video Introduction

<iframe width="560" height="315" src="https://www.youtube.com/embed?v=dbg-E0uM5vc" frameborder="0" allowfullscreen></iframe>



# Introduction

On Monday and Tuesday and Thursday of Week 13 **OR Week 14 (for those who want to submit later)** each group will book a one-hour slot to present and discuss their research final reports with Nick. You can book this here:  [bit.ly/week13_marking_consult](http://www.bit.ly/week13_marking_consult). This presentation and the written final report will be graded on the spot, and feedback given at the same time.

The format will be (1) a 12-minute presentation by your group, with all group members presenting for equal periods of time. This will be followed by (2) questions and discussion, (3) Nick taking time to review your written document, and end with (4) feedback and grading. 

All internal groups will present in their normal class (Wed or Friday) of Week 13.

External groups can nominate to present to the internal class, either via video conference, or pre-recorded video. 

On Wednesday/Friday, when internal groups will present to the whole class, there will be 12 minutes for presentation and ~8 minutes for comments and questions from the class. All students will provide written feedback and grades on each other's presentations via an online Google form. 

If internal groups choose to submit in Week 14, then they won't be expected to present in class in Week 13.

# Presentation

The presentation (on Monday/Tuesday and Thursday) should follow a similar format to the written final report (outlined below). Please check that during your presentation you answer the following questions:

1.	INTRODUCTION: What is your topic? Why is it important?
2.	LITERATURE REVIEW: What does the existing literature say about your topic? What gap in the literature is it seeking to address?
    a.	What is your proposed explanation/theory?
    b.	What are your hypotheses/research questions?
3.	METHODS: What method/s did you use?
    a.	Study 1: Quantitative
    b.	Study 2: Qualitative
4.	RESULTS: What did you find:
    a.	Study 1: Quantitative results in 1-3 tables or figures (max 5)
    b.	Study 2: Qualitative results in 3-10 themes (ideally around 5)
5.	DISCUSSION: What are the implications of your findings, for knowledge and for society at large.

Please use the example of the presentation and slides of a past project (The Hairrifying Truth) - posted on iLearn - as a model for the style of your presentation.

# Written Final Report

The following is a guide to structuring your final report. It is not definitive, and you are free to change or add to it as appropriate, but you must be able to give adequate reasons (in person) for not following this structure if you choose to do so.

Please use the example of final reports, provided on iLearn, as an example of how to structure your final report.

1.	Title (<20 words)
2.	Abstract (<200 words)
3.	Introduction (~700 - 1000 words)
    a.	Opening paragraph/s that explain
        (i)	What is the topic?
        (i)	Why is it interesting and important?
        (i)	What is the puzzle you are seeking to answer? What is the gap in the literature you intend to fill or debate you are seeking to answer?
        (i)	Summary of how you are going to find the answer (the method in one or two sentences).
        (i)	Outline of the structure of the rest of the final report.
    b.	Literature review and background
        i.	Provide any background necessary for the reader to understand and engage with the topic.
        i.	Summarize the existing literature, with a focus on the different theoretical approaches, or causal explanations for the puzzle you are seeking to answer.
        i.	Finish with an explanation of the gap you seek to fill, your proposed explanation/theory, and your hypotheses and/or research questions.
4.	Method (300-1500 words)
    a.	What is your method? How will your method help to answer your question? (i.e. justify your method). Explain your method in detail, including:
        i.	Study 1 (quantitative):
            1.	How did you measure your main variables?
            2.	What analysis did you do (correlation? Regression? Cronbach Alpha)? 
        i.	Study 2 (quantitative)
            1.	What question/s did you ask to get your data? 
            2.	How did you analyse the data (describe your thematic analysis)
5.	Results
    a.	Study 1: Quantitative Analysis
        i.	Present around three (max five) tables or figures
        i.	Definitely present:
            1.	Descriptive statistics table for all major variables (Min, Max, Mean, SD, number valid cases (N))
            2.	Correlation matrix between major variables, particularly the dependent variable, and the main independent variables
        i.	Optional:
            1.	A comparison of mean - t-test - to see if your IV impacts on your DV
            2.	A regression model
            3.	A figure, such as a scattergram with a fitted line to show the relationship between the IV and DV
    b.	Study 2: Qualitative analysis
        i.	Present your 3 - 10 themes (ideally around 5 themes), with each theme having a:
            1.	Subheading
            2.	Short explanation
            3.	Illustrative quote
6.	Discussion
    a.	What is the meaning of your results? 
    b.	Do they agree with your proposed explanation?  Do they agree with the existing literature?
    c.	What are the implication for generalised knowledge, and also for wider society.
7.	Reference list (for anything you cite).
8.	Appendices
    a.	Your survey downloaded as a codebook
    b.	Scan/screenshot of the first page of every reference in your reference list (to prevent plagiarism of references)



