---
title: "SOC830 Lab 8: Testing Hypothesis(t-test)"

lastmod: 2018-12-28T00:00:00.000Z

draft: false
type: docs
maths: true

output:
  blogdown::html_page:
    toc: true

linktitle: "Lab 8: Testing Hypothesis(t-test)"
menu:
  docs:
    parent: SOC830(SOCI702)
    weight: 45
---


<div id="TOC">
<ul>
<li><a href="#import-the-2012-aussa-dataset.">Import the 2012 AuSSa dataset.</a></li>
<li><a href="#one-sample-t-test">One-Sample t-test</a></li>
<li><a href="#two-sample-t-test">Two-Sample t-test</a></li>
<li><a href="#t-test-of-proportion-differences">t-test of Proportion Differences</a></li>
</ul>
</div>

<p>The eighth lab session covers the following:</p>
<ul>
<li>One Sample t-test</li>
<li>Two Sample t-test</li>
<li>t-test of Proportion Difference</li>
</ul>
<p>We will use two packages for this lab. Load them using the following code:</p>
<pre class="r"><code>library(sjlabelled)
library(sjmisc)</code></pre>
<p>Also, run the following code. Otherwise, you will see scientific notations (e.g., <em>2e-16</em>) instead of numbers in the R output</p>
<pre class="r"><code>options(digits=5, scipen=15)</code></pre>
<div id="import-the-2012-aussa-dataset." class="section level1">
<h1>Import the 2012 AuSSa dataset.</h1>
<p>This lab uses the 2012 AuSSa dataset. You can download the file of this dataset in the course website(iLearn). Download the data file and put it in your working directory. Then, run the following code:</p>
<pre class="r"><code>aus2012 &lt;-readRDS(&quot;aussa2012.rds&quot;)</code></pre>
<p>The dataset is loaded as <em>aus2012</em>.</p>
</div>
<div id="one-sample-t-test" class="section level1">
<h1>One-Sample t-test</h1>
<p>The standard working hours per week in Australia is currently 38. Let’s test whether Australians work, on average, less than 38 hours per week. Using a variable of weekly working hours (<em>wrkhrs</em>), we will test whether the average working hours of Australians is less than 38 hours. Thus, our research hypothesis is that Australians work, on average, less than 38 hours per week, and the null hypothesis is that Australians work, on average, 38 or more hours per week. Consequently, we will use a <u><strong>one-tailed t-test</strong></u>. Also, this is <strong>one-sample t-test</strong> because we compare a sample mean with the population mean.
To conduct one-sample t-test, ‘<code>t.test(data name$variable name, mu = a value of comparison)</code>’ is used. In this test, <em>mu</em> is 38 because we compare the average working hours with 38 (hours). Thus, the code is:</p>
<pre class="r"><code>t.test(aus2012$wrkhrs, mu = 38)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  aus2012$wrkhrs
## t = -0.983, df = 958, p-value = 0.33
## alternative hypothesis: true mean is not equal to 38
## 95 percent confidence interval:
##  36.557 38.480
## sample estimates:
## mean of x 
##    37.518</code></pre>
<p>The output shows t-statistic (<em>t = -0.983</em>), degree of freedom (<em>df = 958</em>), and its p-value (<em>p-value = 0.33</em>). It also shows the average working hours per week in the sample (<em>mean of X: 37.518</em>) and 95% confidence interval (<em>36.577</em> to <em>38.480</em>). Let’s set the significance level (alpha) at .05. The p-value in the output is 0.33, but this is based on two-tailed t-test. <u><strong>If you want to get a p-value for one-tailed t-test, you need to divide it by two</strong></u>. Thus, the p-value is 0.165. Since the p-value is greater than alpha (0.165 &gt; 0.05), we fail to reject the null hypothesis. Therefore, it is difficult to argue that Australians work, on average, less than 38 hours per week.</p>
</div>
<div id="two-sample-t-test" class="section level1">
<h1>Two-Sample t-test</h1>
<p>Suppose that we would like to test whether the average working hours are different between men and women. The null hypothesis is that there is no gender difference in average working hours. We use two-sample t-test because we compare the average working hours between two different groups (men and women). Also, this is two-tailed t-test since we do not assume which group works more or less than the other group.</p>
<p>To conduct two-sample t-test, ‘<code>t.test(data name$name of dependent variable  ~ data name$name of independent variable)</code>’ is used. In this test, the dependent variable is working hours (<em>wrkhrs</em>), and the independent variable is gender (<em>sex</em>). Thus, the code is:</p>
<pre class="r"><code>t.test(aus2012$wrkhrs ~ aus2012$sex)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  aus2012$wrkhrs by aus2012$sex
## t = 12.1, df = 917, p-value &lt;0.0000000000000002
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   9.3379 12.9400
## sample estimates:
## mean in group 1 mean in group 2 
##          43.727          32.588</code></pre>
<p>t-statistic is 12.1, and its p-value is less than 0.0000000000000002. The output also shows the average working hours for men (<em>mean in group 1 is 43.727</em>) and for women (<em>mean in group 2 is 32.588</em>). Again, let’s set the significance level (alpha) at .05. The p-value is much less than the alpha. As a result, we reject the null hypothesis and conclude that there is a significant gender difference in working hours per week.</p>
</div>
<div id="t-test-of-proportion-differences" class="section level1">
<h1>t-test of Proportion Differences</h1>
<p>Suppose that we would like to test whether there is a gender difference in the proportion of people who have a favourable view of cohabitation. For the test, we use <em>cohabok</em> which measure whether respondents agree or disagree with the statement that it is all right for a couple to live together without intending to get married. Since <em>cohabok</em> uses a Likert-scale ranging from “Strongly disagree” to “Strongly agree”, we need to recode it into a binary variable in which 1 = “agree” and 0 = “not agree”. Then, we will be able to compute the proportion of people who have a favourable view of cohabitation. The following code recode <em>cohabok</em> in such a way.</p>
<pre class="r"><code>aus2012 &lt;- rec(aus2012, cohabok, rec = &quot;1:2=1; 3:5=0&quot;, append = TRUE)
aus2012$cohabok_r &lt;- set_labels(aus2012$cohabok_r, 
                    labels = c(&quot;agree&quot; = 1, &quot;do not agree&quot; = 0))</code></pre>
<p>Let’s conduct two-sample t-test of proportion difference. We test whether there is a significant gender difference in the proportion of people who have a favourable view of cohabitation. Thus, the dependent variable is the newly recoded variable, <em>cohabok_r</em>, and the independent variable is gender (<em>sex</em>). Run the following code:</p>
<pre class="r"><code>t.test(aus2012$cohabok_r ~ aus2012$sex)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  aus2012$cohabok_r by aus2012$sex
## t = -3.08, df = 1410, p-value = 0.0021
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.119276 -0.026491
## sample estimates:
## mean in group 1 mean in group 2 
##         0.65882         0.73171</code></pre>
<p>t-statistic is -3.08 and its p-value is 0.0021. Again, let’s set the significance level (alpha) at .05. The p-value is much less than alpha. As a result, we reject the null hypothesis and conclude that there is a significant gender difference in the proportion of people who have a favourable view of cohabitation</p>
<p>The R codes you have written so far look like:</p>
<pre class="r"><code>###############################################################################
# Week10: Hypothesis Testing
# 13/05/2019
# SOC830, SOCI702, SOCX830
################################################################################

# Load packages.
library(sjlabelled)
library(sjmisc)

# Run the following code, which will make R to show numbers 
# instead of scientific notations (such as &#39;2e-16&#39;) for tiny values.
options(digits=5, scipen=15)

# Import the 2012 AuSSA dataset
aus2012 &lt;- readRDS(&quot;aussa2012.RDS&quot;)

# One-sample t-test
# t.test(variable, mu = &quot;a value for the null hypothesis&quot;)
t.test(aus2012$wrkhrs, mu = 38)

# Two-sample t-test
t.test(aus2012$wrkhrs ~ aus2012$sex)

# t-test of Proportion Differences
aus2012 &lt;- rec(aus2012, cohabok, rec = &quot;1:2=1; 3:5=0&quot;, append = TRUE)
aus2012$cohabok_r &lt;- set_labels(aus2012$cohabok_r, 
                    labels = c(&quot;agree&quot; = 1, &quot;do not agree&quot; = 0))

t.test(aus2012$cohabok_r ~ aus2012$sex)</code></pre>
<center>
Last updated on <em>13 May, 2019</em> by <em>Dr Hang Young Lee</em><a href="mailto:hangyoung.lee@mq.edu.au">(hangyoung.lee@mq.edu.au)</a>
</center>
</div>
