---
title: "SOC830 Lab 11: Multiple Regression"

lastmod: 2018-12-28T00:00:00.000Z

draft: false
type: docs
maths: true

output:
  blogdown::html_page:
    toc: true

linktitle: "Lab 11: Multiple Regression"
menu:
  docs:
    parent: SOC830(SOCI702)
    weight: 60
---


<div id="TOC">
<ul>
<li><a href="#multiple-regression-analysis">Multiple Regression Analysis</a></li>
<li><a href="#dummy-variable-analysis">Dummy Variable Analysis</a><ul>
<li><a href="#creating-a-dummy-variable.">Creating a Dummy Variable.</a></li>
<li><a href="#assigning-variable-labels">Assigning Variable Labels</a></li>
</ul></li>
<li><a href="#dummy-variable-regression-analysis">Dummy Variable Regression Analysis</a></li>
<li><a href="#creating-a-regression-table">Creating a Regression Table</a></li>
</ul>
</div>

<p>The final lab introduces 1) how to conduct a multiple regression model, 2).how to use dummy variables in the regression model, and 3) how to create regression tables using R. We use four packages in this lab. Load them using the following code:</p>
<pre class="r"><code>library(dplyr)
library(sjlabelled)
library(sjmisc)
library(sjPlot)</code></pre>
<p>Also, run the following code. Otherwise, you will see scientific notations (e.g., 2e-16) instead of numbers in the R output.</p>
<pre class="r"><code>options(digits=5, scipen=15)</code></pre>
<p>This lab uses the 2009 AuSSa dataset. Download the data file in the course website(iLearn) and put it in your working directory. Then, run the following code:</p>
<pre class="r"><code>aus2009 &lt;-readRDS(&quot;aussa2009.rds&quot;)</code></pre>
<p>Using the 2009 AuSSa dataset, this lab investigates gender income gaps in Australia. For this investigation, we will use six variables: gender (<em>sex</em>), education (<em>educyrs</em>), employment status (<em>wrkst</em>), supervisor status (<em>wrksup</em>), working hours per week (<em>wrkhrs</em>) and annual income (<em>rinc</em>). We also add a variable of identification numbers (<em>id</em>) to this dataset. We create a new dataset consisting of only complete cases which have no missing values on the six variables of our choice. The following code performs this task. If you cannot understand the code, review <a href="https://methods101.com/docs/soc830_lab_10/#creating-a-dataset-of-complete-cases">Creating a Dataset of Complete Cases</a>.</p>
<pre class="r"><code>income &lt;- aus2009 %&gt;%
  select(id, sex, educyrs, wrkst, wrksup, wrkhrs, rinc)

income &lt;- income %&gt;%
  mutate(mark = 0)

income &lt;- income %&gt;%
  mutate(mark = replace(mark, complete.cases(income), 1))

income &lt;- income %&gt;%
  filter(mark == 1)</code></pre>
<div id="multiple-regression-analysis" class="section level1">
<h1>Multiple Regression Analysis</h1>
<p>Running regression models is quite simple. We use ‘<code>lm()</code>’ again but add more independent variables. Thus, ‘<code>model name &lt;- lm(dependent ~ independent 1 + independent 2 + independent 3 + …, data = data name)</code>’ conducts multiple regression analysis. The following code estimates a regression model in which education (<em>educyrs</em>) and working hours per week (<em>wrkhrs</em>) explain the annual income(<em>rinc</em>).</p>
<pre class="r"><code>model &lt;- lm(rinc ~ educyrs + wrkhrs, data = income)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rinc ~ educyrs + wrkhrs, data = income)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -81451 -16559  -2982  17717  88216 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept) -12938.1     4758.5   -2.72              0.0067 ** 
## educyrs       2668.0      271.5    9.83 &lt;0.0000000000000002 ***
## wrkhrs         737.8       67.2   10.99 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 25600 on 732 degrees of freedom
## Multiple R-squared:  0.235,  Adjusted R-squared:  0.232 
## F-statistic:  112 on 2 and 732 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>In the output, the intercept is -12,938.1, which means that the annual income will be - <span>$</span>12,938.1 if people have 0 years of schooling and do not work. The coefficient of <em>educyrs</em> is 2,668, which means that for each additional one-year increase in years of schooling, annual income will increase by <span>$</span>2,668 <u>while controlling for the effect of working hours per week</u>. This positive effect of education is statistically significant at <span>α</span> = .05 because the p-value (&lt;0.0000000000000002) is much less than .05. The coefficient of <em>wrkhrs</em> is 737.8, which means that for each additional one-hour increase in working hours per week, annual income will increase by <span>$</span>737.8 <u>while controlling for the effect of education</u>. This positive effect of working hours is statistically significant at <span>α</span> = .05 because the p-value (&lt;0.0000000000000002) is much less than .05. Thus, the regression equation of this model is <span class="math inline">\(rinc = 2,688 × educyrs + 737.8 × wrkhrs – 12,938.1\)</span>. The coefficient of determination (Multiple R-squared) is 0.235, which means that 23.5% of the total variance in annual incomes is explained by the two independent variables.</p>
</div>
<div id="dummy-variable-analysis" class="section level1">
<h1>Dummy Variable Analysis</h1>
<div id="creating-a-dummy-variable." class="section level2">
<h2>Creating a Dummy Variable.</h2>
<p>A dummy variable is a binary variable used in regression analysis that represents subgroups (or categories) of the sample in your study. And it is used to estimate the effect of nominal variables. Let’s make a dummy variable of gender. The following code shows two categories of gender (<em>sex</em>): male and female.</p>
<pre class="r"><code>frq(income$sex)</code></pre>
<pre><code>## 
## # R: Sex (x) &lt;numeric&gt; 
## # total N=735  valid N=735  mean=1.53  sd=0.50
##  
##  val  label frq raw.prc valid.prc cum.prc
##    1   Male 346   47.07     47.07   47.07
##    2 Female 389   52.93     52.93  100.00
##   NA     NA   0    0.00        NA      NA</code></pre>
<p>Since we want to investigate how much less women earn compared to men, males should be the reference category which takes 0. Consequently, females should take 1. Thus, let’s recode <em>sex</em> in such a way. In a nutshell, <strong><u>the reference category must take 0 values in dummy variables</u></strong>.</p>
<pre class="r"><code>income &lt;- rec(income, sex, rec = &quot;1=0;2=1&quot;, append = TRUE)</code></pre>
<p>Then, we rename a newly recoded variable as <em>female</em> and set a variable and value label.</p>
<pre class="r"><code>income &lt;- var_rename(income, sex_r = female)
income$female &lt;- set_label(income$female, label = &quot;Gender&quot;)
income$female &lt;- set_labels(income$female, labels = c(&quot;Male&quot; = 0, &quot;Female&quot; = 1))</code></pre>
<p>The most important step is to <u>change this dummy variable as a factor</u>. Otherwise, R will not treat it as a dummy variable in regression analysis.</p>
<pre class="r"><code>income$female &lt;- to_factor(income$female)</code></pre>
<p>In some cases, you may want to use women instead of men as your reference category. In this case, you can easily change a reference category by using the ‘<code>ref_lvl(variable, lvl = value for the reference category)</code>’ function. Make sure that the variable used for ‘<code>ref_lvl()</code>’ should be a variable that is converted to a factor. The following code makes a new variable (<em>male</em>) in which 0 is female, and 1 is male.</p>
<pre class="r"><code>income$male &lt;- ref_lvl(income$female, lvl = 1)</code></pre>
<p>The following code makes a dummy variable of employment status (<em>wrkst</em>). wrkst has ten categories, which is too many to analyse them. When you look at the frequency table of wrkst, value 4 to 10 can be collapsed into one employment status, ‘not in labour force”. We will use this category as a reference category.</p>
<pre class="r"><code>frq(aus2009$wrkst)</code></pre>
<pre><code>## 
## # R: Current employment status (x) &lt;numeric&gt; 
## # total N=1525  valid N=1488  mean=4.14  sd=3.17
##  
##  val                                label frq raw.prc valid.prc cum.prc
##    1         Employed-full time, main job 579   37.97     38.91   38.91
##    2         Employed-part time, main job 206   13.51     13.84   52.76
##    4                Helping family member  25    1.64      1.68   54.44
##    5                           Unemployed  23    1.51      1.55   55.98
##    6 Student, school, vocational training  44    2.89      2.96   58.94
##    7                              Retired 336   22.03     22.58   81.52
##    8         Housewife, -man, home duties 171   11.21     11.49   93.01
##    9                 Permanently disabled  71    4.66      4.77   97.78
##   10            Other,not in labour force  33    2.16      2.22  100.00
##   NA                                   NA  37    2.43        NA      NA</code></pre>
<pre class="r"><code>income &lt;- rec(income, wrkst, rec = &quot;1=1; 2=2; 4:10=0&quot;, append = TRUE)
income$wrkst_r &lt;- set_label(income$wrkst_r, label = &quot;Current employment status&quot;)
income$wrkst_r &lt;- set_labels(income$wrkst_r, labels = c(&quot;Not in labour force&quot; = 0,
                                                        &quot;Full-time&quot; = 1,
                                                        &quot;Part-time&quot; = 2))
income$wrkst_r &lt;- to_factor(income$wrkst_r)</code></pre>
<p>The following code makes a dummy variable of supervisor status (<em>wrksup</em>). Supervisees are treated as a reference category.</p>
<pre class="r"><code>frq(income$wrksup)</code></pre>
<pre><code>## 
## # R: Supervises others at work (x) &lt;numeric&gt; 
## # total N=735  valid N=735  mean=1.49  sd=0.50
##  
##  val label frq raw.prc valid.prc cum.prc
##    1   Yes 374   50.88     50.88   50.88
##    2    No 361   49.12     49.12  100.00
##   NA    NA   0    0.00        NA      NA</code></pre>
<pre class="r"><code>income &lt;- rec(income, wrksup, rec = &quot;1=1; 2=0&quot;, append = TRUE)
income$wrksup_r &lt;- set_label(income$wrksup_r, label = &quot;Supervisor jobs&quot;)
income$wrksup_r &lt;- set_labels(income$wrksup_r, labels = c(&quot;Suvervisee&quot; = 0,
                                                          &quot;Supervisor&quot; = 1))
income$wrksup_r &lt;- to_factor(income$wrksup_r)</code></pre>
</div>
<div id="assigning-variable-labels" class="section level2">
<h2>Assigning Variable Labels</h2>
<p>We also assign variable labels to all the other variables of the income dataset.</p>
<pre class="r"><code>income$educyrs &lt;- set_label(income$educyrs, label = &quot;Education&quot;)
income$wrkhrs &lt;- set_label(income$wrkhrs, label = &quot;Hours worked per week&quot;)
income$rinc &lt;- set_label(income$rinc, label = &quot;Annual income&quot;)</code></pre>
</div>
</div>
<div id="dummy-variable-regression-analysis" class="section level1">
<h1>Dummy Variable Regression Analysis</h1>
<p>First, we estimate the annual income only by gender, which shows gender difference in the annual income.</p>
<pre class="r"><code>model.4.1 &lt;- lm(rinc ~ female, data = income)
summary(model.4.1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rinc ~ female, data = income)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -65099 -22495    -99  19105  58105 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)    65099       1485   43.83 &lt;0.0000000000000002 ***
## female1       -19204       2042   -9.41 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 27600 on 733 degrees of freedom
## Multiple R-squared:  0.108,  Adjusted R-squared:  0.106 
## F-statistic: 88.5 on 1 and 733 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>In the output, ‘female1’ indicates ‘being a female (when the value of female is 1). Thus, the coefficient of ‘female1’ means that women earn <span>$</span>19,204 less than men. And this female disadvantage is statistically significant (the p-value is less than .001).</p>
<p>For the comparison, let’s use <em>male</em> instead of <em>female</em> in regression analysis. Note that ‘female’ is the reference category in the <em>male</em> variable.</p>
<pre class="r"><code>model.4.1.1 &lt;- lm(rinc ~ male, data = income)
summary(model.4.1.1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rinc ~ male, data = income)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -65099 -22495    -99  19105  58105 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)    45895       1401   32.76 &lt;0.0000000000000002 ***
## male1          19204       2042    9.41 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 27600 on 733 degrees of freedom
## Multiple R-squared:  0.108,  Adjusted R-squared:  0.106 
## F-statistic: 88.5 on 1 and 733 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>In the output, look at the coefficient of ‘male1’. It is 19,204. Note that it is a <strong>POSITIVE</strong> number. It means that men earn <span>$</span>19,204 <strong>MORE</strong> than women. This example shows well that regression coefficients change when different categories are set as a reference category and that the interpretation of coefficients for dummy variables should be made in relation to assigned reference categories.</p>
<p>The second model estimates female disadvantage in the annual income while controlling for education.</p>
<pre class="r"><code>model.4.2 &lt;- lm(rinc ~ female + educyrs, data = income)
summary(model.4.2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rinc ~ female + educyrs, data = income)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -63729 -17900  -2893  19989  59271 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)    24743       4136    5.98         0.0000000034 ***
## female1       -19715       1908  -10.33 &lt; 0.0000000000000002 ***
## educyrs         2836        274   10.36 &lt; 0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 25800 on 732 degrees of freedom
## Multiple R-squared:  0.222,  Adjusted R-squared:  0.22 
## F-statistic:  104 on 2 and 732 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>After controlling education, the coefficient of <em>female</em> drops to -19,715, which means that women earn <span>$</span>19,715 less than men who have the same level of education.</p>
<p>The third model estimates female disadvantage in the annual income while controlling for education and working hours per week.</p>
<pre class="r"><code>model.4.3 &lt;- lm(rinc ~ female + educyrs + wrkhrs, data = income)
summary(model.4.3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rinc ~ female + educyrs + wrkhrs, data = income)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -73473 -15943  -2091  17612  75984 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)    361.3     4917.4    0.07                 0.94    
## female1     -14496.9     1929.2   -7.51  0.00000000000016727 ***
## educyrs       2743.1      262.0   10.47 &lt; 0.0000000000000002 ***
## wrkhrs         571.0       68.5    8.34  0.00000000000000036 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 24700 on 731 degrees of freedom
## Multiple R-squared:  0.289,  Adjusted R-squared:  0.287 
## F-statistic: 99.3 on 3 and 731 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>After controlling education and working hours per week, the coefficient of <em>female</em> reduced to -14,496, which means that women earn <span>$</span>14,496 less than men <u>if they have the same level of education and work as much as men do</u>. This reduction implies that women work less than men, which in turn decreases their annual income.</p>
<p>The fourth model adds another dummy variable, employment status (<em>wrkst_r</em>).</p>
<pre class="r"><code>model.4.4 &lt;- lm(rinc ~ female + educyrs + wrkhrs + wrkst_r, data = income)
summary(model.4.4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rinc ~ female + educyrs + wrkhrs + wrkst_r, data = income)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -69347 -15734  -1928  16941  76334 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) -18471.8     7654.2   -2.41              0.01606 *  
## female1     -12781.4     1889.4   -6.76       0.000000000027 ***
## educyrs       2551.5      255.7    9.98 &lt; 0.0000000000000002 ***
## wrkhrs         309.9       90.7    3.42              0.00067 ***
## wrkst_r1     35211.0     5827.7    6.04       0.000000002427 ***
## wrkst_r2     22627.1     6079.8    3.72              0.00021 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 24000 on 729 degrees of freedom
## Multiple R-squared:  0.333,  Adjusted R-squared:  0.328 
## F-statistic: 72.8 on 5 and 729 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>The output shows two coefficients of employment status (<em>wrkst_r</em>). In <em>wrkst_r</em>, 1 means “Full-time employment”, and 2 means “Part-time employment”. Thus, the coefficient of ‘wrkst_r1’ is for “Full-time employment and that of ‘wrkst_r2’ is for “Part-time employment”. The interpretation is that full-time workers earn <span>$</span>35,211 more, and part-time workers earn <span>$</span>22,627 more than those who are not in the labour force (the reference category) <u>while controlling for gender, education and working hours per week</u>. After controlling employment status as well as education and working hours per week, women earn <span>$</span>12,781 less than men. The gender gap is reduced a lot compared to that in the second model, which implies that employment status accounts substantially for female disadvantage in the annual income. Women are less likely to have stable jobs than men, which decrease their annual income.</p>
<p>The fifth model adds a dummy variable of supervisor status, <em>wrksup_r</em>.</p>
<pre class="r"><code>model.4.5 &lt;- lm(rinc ~ female + educyrs + wrkhrs + wrkst_r + wrksup_r, data = income)
summary(model.4.5)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rinc ~ female + educyrs + wrkhrs + wrkst_r + wrksup_r, 
##     data = income)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -71303 -14958  -1293  16018  77518 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)   -17601       7563   -2.33              0.02023 *  
## female1       -12462       1868   -6.67        0.00000000005 ***
## educyrs         2367        256    9.24 &lt; 0.0000000000000002 ***
## wrkhrs           238         91    2.62              0.00904 ** 
## wrkst_r1       35738       5758    6.21        0.00000000091 ***
## wrkst_r2       22764       6005    3.79              0.00016 ***
## wrksup_r1       7992       1824    4.38        0.00001346487 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 23700 on 728 degrees of freedom
## Multiple R-squared:  0.35,   Adjusted R-squared:  0.345 
## F-statistic: 65.4 on 6 and 728 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>The coefficient of ‘wrksup_r1’ (which means those who supervise others at work) is 7,992. This means that supervisors earn <span>$</span>7,992 more than supervisees <u>while controlling for gender, education, working hours per week and employment status</u>. The coefficient of ‘female1’ is a little bit changed, implying that supervisor status does not contribute much to female disadvantage in the annual income. The regression equation of this model is <span class="math inline">\(rinc =-12,462 × female + 2,367 × educyrs + 238 × wrkhrs + 35,738 × wrkst_r1 + 22,764 × wrkst_r2 +7,992 × wrksup_r1 – 17,601\)</span>. R-square (Multiple R-squared) is 0.35, which means that 35% of the total variance in the annual income is explained by the five variables (gender, education, working hours, employment status, and supervisor status).</p>
</div>
<div id="creating-a-regression-table" class="section level1">
<h1>Creating a Regression Table</h1>
<p>We have so far analysed female disadvantage in the annual income using several regression models. How can we present all these regression models in a just single table? Using the ‘<code>tab_model()</code>’ function would be the easiest way. The following code combines the five regression models we have estimated so far and creates a single regression table.</p>
<pre class="r"><code>tab_model(model.4.1, model.4.2, model.4.3, model.4.4, model.4.5, digits = 3,
          pred.labels = c(&quot;Intercept&quot;, &quot;Female (ref. = Male)&quot;, 
                          &quot;Education&quot;, &quot;Hours worked per week&quot;, 
                          &quot;Full-time (ref. = Not in labour force)&quot;, 
                          &quot;Part-time (ref. = Not in labour force)&quot;, 
                          &quot;Supervisor (ref. = Supervisee)&quot;),
          dv.labels = c(&quot;Model 1&quot;, &quot;Model 2&quot;, &quot;Model 3&quot;, &quot;Model 4&quot;, &quot;Model 5&quot;),
          title = &quot;Gender Effects on Annual Income&quot;,
          show.se = TRUE, show.ci = FALSE, collapse.se = TRUE, p.style = &quot;asterisk&quot;)</code></pre>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Gender Effects on Annual Income
</caption>
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Model 1
</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Model 2
</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Model 3
</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Model 4
</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Model 5
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Intercept
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
65099.191 <sup>***</sup><br>(1485.239)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
24743.249 <sup>***</sup><br>(4135.493)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
361.329 <sup></sup><br>(4917.426)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-18471.756 <sup>*</sup><br>(7654.244)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-17601.103 <sup>*</sup><br>(7563.033)
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Female (ref. = Male)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-19204.178 <sup>***</sup><br>(2041.574)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-19714.886 <sup>***</sup><br>(1908.532)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-14496.910 <sup>***</sup><br>(1929.191)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-12781.385 <sup>***</sup><br>(1889.367)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-12461.921 <sup>***</sup><br>(1867.632)
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Education
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2835.734 <sup>***</sup><br>(273.737)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2743.087 <sup>***</sup><br>(261.986)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2551.511 <sup>***</sup><br>(255.720)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2366.974 <sup>***</sup><br>(256.071)
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Hours worked per week
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
571.010 <sup>***</sup><br>(68.454)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
309.875 <sup>***</sup><br>(90.654)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
238.257 <sup>**</sup><br>(91.022)
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Full-time (ref. = Not in labour force)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
35211.005 <sup>***</sup><br>(5827.722)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
35737.917 <sup>***</sup><br>(5757.544)
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Part-time (ref. = Not in labour force)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
22627.062 <sup>***</sup><br>(6079.790)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
22764.274 <sup>***</sup><br>(6005.349)
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Supervisor (ref. = Supervisee)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
7992.262 <sup>***</sup><br>(1823.718)
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="1">
735
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="1">
735
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="1">
735
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="1">
735
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="1">
735
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="1">
0.108 / 0.106
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="1">
0.222 / 0.220
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="1">
0.289 / 0.287
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="1">
0.333 / 0.328
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="1">
0.350 / 0.345
</td>
</tr>
<tr>
<td colspan="6" style="font-style:italic; border-top:double black; text-align:right;">
<ul>
<li>p&lt;0.05   ** p&lt;0.01   *** p&lt;0.001
</td>
</tr></li>
</ul>
</table>
<p>In the code, you must list the name of regression models that will be included in a regression table. ‘<code>digits = value</code>’ specifies the decimal places for numbers in the table. ‘<code>pred.labels  = c()</code>’ sets the labels of independent variables displayed in the first column of the table. ‘<code>dv.labels = c()</code>’ sets the labels of models displayed in the first row of the table. ‘<code>title = “”</code>’ sets the title of the table. ‘<code>show.se = TRUE</code>’ displays the standard errors of coefficients, ‘<code>show.ci = FALSE</code>’ does not show the confidence intervals of coefficients, and ‘<code>collapse.se = TRUE</code>’ shows standard errors along with coefficients in the same column. ‘<code>p.style = “asterisk”</code>’ displays the p-value in the format of stars.</p>
<p>The R codes you have written so far look like:</p>
<pre class="r"><code>################################################################################
# Lab 11: Multiple Regression
# 3/06/2019
# SOC830, SOCI702, SOCX830
################################################################################
# Load packages
library(dplyr)
library(sjlabelled)
library(sjmisc)
library(sjPlot)

# Avoid scientific notation
options(digits=5, scipen=15) 

# Load dataset
aus2009 &lt;- readRDS(&quot;aussa2009.RDS&quot;)

# Create a dataset of complete cases
income &lt;- aus2009 %&gt;%
  select(id, sex, educyrs, wrkst, wrksup, wrkhrs, rinc)

income &lt;- income %&gt;%
  mutate(mark = 0)

income &lt;- income %&gt;%
  mutate(mark = replace(mark, complete.cases(income), 1))

income &lt;- income %&gt;%
  filter(mark == 1)

# Multiple regression
model &lt;- lm(rinc ~ educyrs + wrkhrs, data = income)
summary(model)

# Make dummy variables
## Gender
frq(income$sex)

income &lt;- rec(income, sex, rec = &quot;1=0;2=1&quot;, append = TRUE)

income &lt;- var_rename(income, sex_r = female) # rename `sex_r` as `female`
income$female &lt;- set_label(income$female, label = &quot;Gender&quot;)
income$female &lt;- set_labels(income$female, labels = c(&quot;Male&quot; = 0, &quot;Female&quot; = 1))

income$female &lt;- to_factor(income$female) # convert into a factor for dummy

income$male &lt;- ref_lvl(income$female, lvl = 1) # set females as a reference

## Current employment status
frq(aus2009$wrkst)
income &lt;- rec(income, wrkst, rec = &quot;1=1; 2=2; 4:10=0&quot;, append = TRUE)
income$wrkst_r &lt;- set_label(income$wrkst_r, label = &quot;Current employment status&quot;)
income$wrkst_r &lt;- set_labels(income$wrkst_r, labels = c(&quot;Not in labour force&quot; = 0,
                                                        &quot;Full-time&quot; = 1,
                                                        &quot;Part-time&quot; = 2))
income$wrkst_r &lt;- to_factor(income$wrkst_r)

## Supervisor
frq(income$wrksup)
income &lt;- rec(income, wrksup, rec = &quot;1=1; 2=0&quot;, append = TRUE)
income$wrksup_r &lt;- set_label(income$wrksup_r, label = &quot;Supervisor jobs&quot;)
income$wrksup_r &lt;- set_labels(income$wrksup_r, labels = c(&quot;Suvervisee&quot; = 0,
                                                          &quot;Supervisor&quot; = 1))
income$wrksup_r &lt;- to_factor(income$wrksup_r)

## Assign Variable Name
income$educyrs &lt;- set_label(income$educyrs, label = &quot;Education&quot;)
income$wrkhrs &lt;- set_label(income$wrkhrs, label = &quot;Hours worked per week&quot;)
income$rinc &lt;- set_label(income$rinc, label = &quot;Annual income&quot;)

# Dummy variable regression analysis
model.4.1 &lt;- lm(rinc ~ female, data = income) # male as the reference
summary(model.4.1)

model.4.1.1 &lt;- lm(rinc ~ male, data = income) # female as the reference
summary(model.4.1.1)

model.4.2 &lt;- lm(rinc ~ female + educyrs, data = income)
summary(model.4.2)

model.4.3 &lt;- lm(rinc ~ female + educyrs + wrkhrs, data = income)
summary(model.4.3)

model.4.4 &lt;- lm(rinc ~ female + educyrs + wrkhrs + wrkst_r, data = income)
summary(model.4.4)

model.4.5 &lt;- lm(rinc ~ female + educyrs + wrkhrs + wrkst_r + wrksup_r, data = income)
summary(model.4.5)

# Make a regression table
tab_model(model.4.1, model.4.2, model.4.3, model.4.4, model.4.5, digits = 3,
          pred.labels = c(&quot;Intercept&quot;, &quot;Female (ref. = Male)&quot;, 
            &quot;Education&quot;, &quot;Hours worked per week&quot;, 
            &quot;Full-time (ref. = Not in labour force)&quot;, 
            &quot;Part-time (ref. = Not in labour force)&quot;, 
            &quot;Supervisor (ref. = Supervisee)&quot;),
          dv.labels = c(&quot;Model 1&quot;, &quot;Model 2&quot;, &quot;Model 3&quot;, &quot;Model 4&quot;, &quot;Model 5&quot;),
          title = &quot;Gender Effects on Annual Income&quot;,
          show.se = TRUE, show.ci = FALSE, collapse.se = TRUE, p.style = &quot;asterisk&quot;)</code></pre>
<center>
Last updated on <em>01 June, 2019</em> by <em>Dr Hang Young Lee</em><a href="mailto:hangyoung.lee@mq.edu.au">(hangyoung.lee@mq.edu.au)</a>
</center>
</div>
