---
title: "SOCI832 999.0 Setup Information"

lastmod: 2018-12-28T00:00:00.000Z

draft: true
type: docs
maths: true

output:
  blogdown::html_page:
    toc: true

linktitle: "999.0 Setup Info"
menu:
  docs:
    parent: SOCI832
    weight: 999
---

<style>
table, th, td, tr, tbody {
  border-top: 1px solid LightGray;
    border-left: 0px solid LightGray;  
    border-right: 0px solid LightGray;  
    border-bottom: 1px solid LightGray;
}
</style>



<table>   <tr>  <td>
# My Chosen Design for Each Page

* Reading
* Concepts (15)
* Summary (300 words)
* Main Text (1600 words divided ~ 4 Sections, each with 4 Paragraphs of about 100 words)

</td>   </tr>  </table>


<table>  <tr>  <td>
# Default Text for Setting Up a New Page

````

---
title: "SOCI832 3.1 An introduction to factor analysis"

lastmod: 2018-12-28T00:00:00.000Z

draft: true
type: docs
maths: true

output:
  blogdown::html_page:
    toc: true

linktitle: "3.1 Dimension: Factor"
menu:
  docs:
    parent: SOCI832
    weight: 310
---

	<style>
table, th, td, tr, tbody {
  border-top: 1px solid LightGray;
    border-left: 0px solid LightGray;  
    border-right: 0px solid LightGray;  
    border-bottom: 1px solid LightGray;
}
</style>

<table>  <tr>  <td>
# Reading

[Field, A., Miles, J., and Field, Z. (2012). *Discovering statistics using R*. Sage publications.](http://a.co/2jVI7VH)

* Chapter X: XXXXXXXXXXXXX
</td>  </tr>  </table>

<table>   <tr>  <td>
# Concepts 

<b style="padding-left: 2em">Level 1<br></b>
<b style="padding-left: 4em">Level 2<br></b>
<b style="padding-left: 6em">Level 3<br></b>
</td>   </tr>  </table>

<table>   <tr>  <td>
# Summary

This is a 300 word summary of clase
</td>   </tr>  </table>


````

</td>   </tr>  </table>


<table>  <tr>  <td>
# File Structure of SOCI832

*  menu weight
*  File structure
*  Menu title
*  Page title

*  10
*  soci832_0_overview_lessons
*  0.1 Overview: Lessons
*  SOCI832: Overview of lessons

*  20
*  soci832_0_overview_assessment
*  0.2 Overview: Assessment
*  SOCI832: Overview of assessment

*  110
*  soci832_1_intro_methods
*  1.1 Intro: Research Methods
*  Lesson 1.1 An introduction to research methods

*  120
*  soci832_1_intro_stats
*  1.2 Intro: Research Methods
*  Lesson 1.2 An introduction to statistics

*  130
*  soci832_1_intro_r
*  1.3 Intro: R
*  Lesson 1.3 An introduction to R

*  140
*  soci832_1_intro_univariate
*  1.4 Intro: Univariate
*  Lesson 1.4 An introduction to univariate analysis

*  210
*  soci832_2_bivar_means
*  2.1 Bivariate: Means
*  Lesson 2.1 An introduction to comparing means

*  220
*  soci832_2_bivar_corr
*  2.2 Bivariate: Correlation
*  Lesson 2.2 An introduction to correlation

*  230
*  soci832_2_bivar_chi
*  2.3 Bivariate: Chi-square
*  Lesson 2.3 An introduction to chi-square tests

*  310
*  soci832_3_dimen_factor
*  3.1 Dimension: Factor
*  Lesson 3.1 An introduction to factor analysis

*  320
*  soci832_3_dimen_index
*  3.2 Dimension: Index
*  Lesson 3.2 An introduction to creating and testing indexes

*  410
*  soci832_4_regress_linear
*  4.1 Regression: Linear
*  Lesson 4.1 An introduction to linear regression

*  420
*  soci832_4_regress_diag
*  4.2 Regression: Diagnostics
*  Lesson 4.2 Regression diagnostics

*  430
*  soci832_4_regress_logit
*  4.3 Regression: Logit
*  Lesson 4.3 An introduction to logistic regression

*  440
*  soci832_4_regress_other
*  4.4 Regression: Other
*  Lesson 4.4 Other types of regression

*  510
*  soci832_5_path_moderators
*  5.1 Path analysis: Moderators
*  Lesson 5.1 An introduction to moderating variables

*  520
*  soci832_5_path_mediators
*  5.2 Path analysis: Mediators
*  Lesson 5.2 An introduction to mediating variables

*  530
*  soci832_5_path_path_analysis
*  5.3 Path analysis: An introduction to path analysis
*  Lesson 5.3 An introduction to path analysis

*  610
*  soci832_6_present_report
*  6.1 Present: Reports
*  Lesson 6.1 Presenting statistical analysis in reports

*  620
*  soci832_6_present_ggplot
*  6.2 Present: Graphs
*  Lesson 6.2 An introduction to graphs in ggplot

*  999
*  soci832_999_setup_info
*  999.0 Setup Info
*  SOCI832 999.0 Setup Information
</td>  </tr>  </table>


<table>   <tr>  <td>
# Table 3
</td>   </tr>  </table>

