---
title: "SOCI832 Lesson 1.4: Univariate analysis"

lastmod: 2018-12-28T00:00:00.000Z

draft: false
type: docs
maths: true	

output:
  blogdown::html_page:
    toc: true

linktitle: "1.4 Intro: Univariate stats"
menu:
  docs:
    parent: SOCI832
    weight: 140

---


<div id="TOC">
<ul>
<li><a href="#overview">Overview</a><ul>
<li><a href="#what-does-this-lesson-deal-with">What does this lesson deal with?</a></li>
<li><a href="#what-does-this-teach-me-about-r">What does this teach me about R?</a></li>
<li><a href="#what-does-this-teach-me-about-statistics">What does this teach me about statistics?</a></li>
<li><a href="#tips-comments-trivia">Tips, Comments, Trivia</a></li>
<li><a href="#stuff-you-need-to-do-before-starting">Stuff you need to do before starting</a></li>
</ul></li>
<li><a href="#lesson-1-basic-univariate-functions">Lesson 1: Basic Univariate Functions</a><ul>
<li><a href="#mean">1.1 Mean</a></li>
<li><a href="#variance-and-standard-deviation">1.2 Variance and standard deviation</a></li>
</ul></li>
<li><a href="#lesson-2-basic-univariate-visualisation">Lesson 2: Basic Univariate Visualisation</a><ul>
<li><a href="#histogram-example-1-likelihood-of-voting">Histogram Example 1: Likelihood of voting</a></li>
</ul></li>
<li><a href="#lesson-3-univariate-statistics-with-summarytools">Lesson 3: Univariate statistics with summarytools</a><ul>
<li><a href="#resources">RESOURCES</a></li>
<li><a href="#why-use-it">WHY USE IT?</a></li>
<li><a href="#core-functions-freq-ctable-descr-dfsummary.">CORE FUNCTIONS: freq(), ctable(), descr(), dfSummary().</a></li>
<li><a href="#tips">TIPS:</a></li>
<li><a href="#lesson-3.1-freq-function">LESSON 3.1: freq() function</a><ul>
<li><a href="#dont-do-this">3.1.1 Don’t do this</a></li>
<li><a href="#basic-command">3.1.2 Basic command</a></li>
<li><a href="#settings">3.1.3 Settings</a></li>
<li><a href="#putting-it-all-together">3.1.4. Putting it all together</a></li>
<li><a href="#save-to-file">3.1.5. Save to file</a></li>
</ul></li>
<li><a href="#lesson-3.2-descr-function">Lesson 3.2: descr() function</a></li>
<li><a href="#lesson-3.3-dfsummary-function">Lesson 3.3: dfSummary() function</a></li>
</ul></li>
</ul>
</div>

<p>Last updated: 27 Dec 2018</p>
<p><em><em>Author</em>: Nicholas Harrigan</em></p>
<div id="overview" class="section level1">
<h1>Overview</h1>
<div id="what-does-this-lesson-deal-with" class="section level3">
<h3>What does this lesson deal with?</h3>
<ul>
<li>Introduces methods for making univariate statistics in R</li>
</ul>
</div>
<div id="what-does-this-teach-me-about-r" class="section level3">
<h3>What does this teach me about R?</h3>
<ol style="list-style-type: decimal">
<li>Basic commands for univariate statistics</li>
<li>Handy packages and tricks for getting your data in publishable formats (e.g. table out; summary stats; etc.)</li>
</ol>
</div>
<div id="what-does-this-teach-me-about-statistics" class="section level3">
<h3>What does this teach me about statistics?</h3>
<p>Honestly most of the statistical knowledge is assumed as it can be found in a simple google search or any simple stats textbook.</p>
</div>
<div id="tips-comments-trivia" class="section level3">
<h3>Tips, Comments, Trivia</h3>
<p>The introduction to the package summarytools, continues into the next script (Week 2, Part 2), because one of the tools creates cross-tabulations of two variables (i.e. a bivariate cross tabulation)</p>
</div>
<div id="stuff-you-need-to-do-before-starting" class="section level3">
<h3>Stuff you need to do before starting</h3>
<ol style="list-style-type: decimal">
<li>Change this to your working directory</li>
</ol>
<pre class="r"><code>setwd(&quot;C:/G/2018, SOCI832/Datasets/AES 2013/&quot;)</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><p>Put the file “elect_2013.csv” into that folder. This file can be found here: <a href="https://mqsociology.github.io/learn-r/soci832/elect_2013.csv" class="uri">https://mqsociology.github.io/learn-r/soci832/elect_2013.csv</a></p></li>
<li><p>Keep the codebook openned in a browser so you can refer to it when you need it. The codebook is here: <a href="https://mqsociology.github.io/learn-r/soci832/codebook%20aes%202013.html">https://mqsociology.github.io/learn-r/soci832/codebook%20aes%202013.html</a></p></li>
<li><p>Import the data</p></li>
</ol>
<pre class="r"><code>library(readr)
elect_2013 &lt;- read_csv(&quot;elect_2013.csv&quot;) # loads dataset</code></pre>
<pre><code>## Warning: Missing column names filled in: &#39;X1&#39; [1]</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Remove the first column which is not needed.</li>
</ol>
<p>FYI the command works by saying “copy all columns except the first”.</p>
<p><em>NOTE: Only run this command once after you run the ‘read.csv’ command. Each time you run it, it deletes the first variable.</em></p>
<pre class="r"><code>elect_2013 &lt;- elect_2013[,2:ncol(elect_2013)]</code></pre>
</div>
</div>
<div id="lesson-1-basic-univariate-functions" class="section level1">
<h1>Lesson 1: Basic Univariate Functions</h1>
<p>This section introduces the basic functions for running univariate statistics. In most cases there are are easier commands to run, but we will learn about those later.</p>
<div id="mean" class="section level2">
<h2>1.1 Mean</h2>
<p>Mean is just the sum of a variable/number of cases. There is a built in function that calcuates the mean</p>
<pre class="r"><code>mean(elect_2013$likelihood_vote)</code></pre>
<pre><code>## [1] NA</code></pre>
<p>Oh damn! We got <code>[1] NA</code></p>
<p>This happens because there are missing values in the variable ‘likelihood_vote’. Why are there missing values? Because some people didn’t answer that survey question.</p>
<p>There is an easy way to deal with this. We add one more argument* to the function** ‘mean()’. The argument is ‘na.rm = TRUE’</p>
<pre class="r"><code>mean(elect_2013$likelihood_vote, na.rm = TRUE)</code></pre>
<pre><code>## [1] 4.362201</code></pre>
<p>We can get the median with:</p>
<pre class="r"><code>median(elect_2013$likelihood_vote, na.rm = TRUE)</code></pre>
<pre><code>## [1] 5</code></pre>
<p>We can also extract various quartiles and quintiles. The default setting gives us min, max, 25%, 50%, and 75%</p>
<pre class="r"><code>quantile(elect_2013$likelihood_vote, na.rm = TRUE)</code></pre>
<pre><code>##   0%  25%  50%  75% 100% 
##    1    4    5    5    5</code></pre>
<p>We can also specify particular probablities with the argument ‘probs =’</p>
<pre class="r"><code>quantile(elect_2013$likelihood_vote, na.rm = TRUE, probs = c(0, 0.2, 0.4, 0.6, 
    0.8, 1))</code></pre>
<pre><code>##   0%  20%  40%  60%  80% 100% 
##    1    4    5    5    5    5</code></pre>
<p>NOTE: when we provide the ‘probs’ argument, we need specify the set of numbers inside the function ‘c()’.</p>
<p>‘c()’ is a function in R which joins together a set of numbers and makes them into a vector.</p>
<p>Vectors are particular data type, but in essence they are set of numbers, like row or column.</p>
<p>The thing to note is just that some functions and some arguments in R will need numbers passed to them is special ways. Some will need them passed in ‘c()’, others will need them passed in double inverted commas “”, and some other formats. The main thing at this stage is to know to look out for this, as they are the sort of typo that will cause bugs in your code, and frustrate you for hours as you try to work out why your code isn’t working.</p>
</div>
<div id="variance-and-standard-deviation" class="section level2">
<h2>1.2 Variance and standard deviation</h2>
<p>Variance and standard deviation are calculated with very simple commands: var() and sd()</p>
<pre class="r"><code>var(elect_2013$likelihood_vote, na.rm = TRUE)</code></pre>
<pre><code>## [1] 1.147758</code></pre>
<pre class="r"><code>sd(elect_2013$likelihood_vote, na.rm = TRUE)</code></pre>
<pre><code>## [1] 1.071335</code></pre>
<p>Let’s now compare out results with those of McAllister 2016. If you haven’t already, download the article from here: <a href="https://doi.org/10.1080/13676261.2016.1154936" class="uri">https://doi.org/10.1080/13676261.2016.1154936</a></p>
<p>Once you have downloaded it go and look at Appendix 1 and look at the mean of the first variable ‘Likelihood of voting’ and compare the mean reported with the mean we calculated.</p>
<p>You will notice that the mean which they report (4.20) is different to ours (4.362201).</p>
<p>Why do you think this is?</p>
<p>One reason is that McAllister 2016 reports ‘weighted means’.</p>
<p>What does that mean?</p>
<p>It means that the cases (i.e. the respondants in the survey) are given different weightings when calcuating statistics.</p>
<p>Why does he do this?</p>
<p>Because the survey aims to be representative of the Australian population but has the problem that the people who did the survey are systematically different from the Australian population? How? We don’t know exactly, but generally there tends to be overrepresentation of educated and older persons in surveys.</p>
<p>Regardless, McAllister and the people who collected this data have calculated a number that represents how much we should weight each person in this survey. People who from over-represented demographics will have a value for the variable ‘weight’ below 1, e.g. 0.6 While those who are from under-represented demographics will have higher weights (up to 6).</p>
<p>We are lucky that many of the statistical functions in R have a way to incorporate weighting into their calculations.</p>
<p>For mean, there is a special command ‘weighted.mean’. Note that we use three arguments: * the variable we are calculating the mean on * the weighting variable * the command to remove cases with missing values.</p>
<pre class="r"><code>weighted.mean(elect_2013$likelihood_vote, 
              w = elect_2013$weight, na.rm =  TRUE)</code></pre>
<pre><code>## [1] 4.201089</code></pre>
<p>What weighted mean do you get? Is it similar to that reported in McAllister, Appendix 1 (he reports 4.20)?</p>
</div>
</div>
<div id="lesson-2-basic-univariate-visualisation" class="section level1">
<h1>Lesson 2: Basic Univariate Visualisation</h1>
<p>This section we are going to learn one simple univariate visualisation: the histogram.</p>
<p>A histogram is one of the most basic and fundamental graphs in statistics. It graphs only one variable. The x-axis of a histogram is the various values of the variable, while the y-axis is the count of cases (units of analysis) that have each value of the variable. Variables displayed in histograms must be discrete (i.e. they need to have a limited number of values, eg. 1,2,3,…). They can’t be perfectly continuous (e.g. 1.00123, 1.3233, etc). One of the ways which we deal with the need for discrete variables in a histogram is that we often create ‘bins’. Bins collect cases (units of analysis) who all have a value for the variable that is in a particular range.</p>
<p>We actually use ‘bins’ in lots of different statistical applications. For example, say we have a survey question where respondents have given their age (between 0 and 120). Often we transform that into a smaller number of variables such as 0-19, 20-39, 40-59, etc. Each of these categories, e.g. 0-19, is a ‘bin’.</p>
<p>R has a built in histogram command (called ‘hist()’), but when I have been testing it, and reading about it, I’ve found that there is some problems that make it unreliable, so I’m going to teach another simple method.</p>
<p>We are going to use two commands: ‘table()’ and ‘barplot()’.</p>
<div id="histogram-example-1-likelihood-of-voting" class="section level2">
<h2>Histogram Example 1: Likelihood of voting</h2>
<p>First, let’s see what table() does</p>
<pre class="r"><code>table(elect_2013$likelihood_vote)</code></pre>
<pre><code>## 
##    1    2    3    4    5 
##  126  269  236  721 2574</code></pre>
<p>So of the 3955 respondents to our survey, 126 said that they would definitely not vote if voting was voluntary, while 2574 said they definitely would vote.</p>
<p>We can visualise this with the the ‘barplot()’ function:</p>
<pre class="r"><code>barplot(table(elect_2013$likelihood_vote))</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-13"></span>
<img src="/docs/soci832_1_intro_univariate_files/figure-html/unnamed-chunk-13-1.png" alt="Histogram of the likelihood to vote" width="672" />
<p class="caption">
Figure 1: Histogram of the likelihood to vote
</p>
</div>
<p>in the ‘Plots’ windown on the bottom right corner of RStudio, you will see these five numbers graphed as a histogram.</p>
<p>Often we want to graph a histogram as a probability density graph, where the y-axis is the proportion of cases in each bin. To do this we need to confirm the number of cases (removing those that are missing) The number of cases can be calculated with the following code:</p>
<pre class="r"><code>cases &lt;- length(elect_2013$likelihood_vote
            [!is.na(elect_2013$likelihood_vote)])</code></pre>
<p>To see how many cases there are, just type ‘cases’ and view the contents of the cases variable.</p>
<pre class="r"><code>cases</code></pre>
<pre><code>## [1] 3926</code></pre>
<p>There are 3926 cases (from a total of 3955 people who did the survey).</p>
<p>To display the histogram as a probablity density, we just run:</p>
<pre class="r"><code>barplot(table(elect_2013$likelihood_vote)/cases)</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-16"></span>
<img src="/docs/soci832_1_intro_univariate_files/figure-html/unnamed-chunk-16-1.png" alt="Probability distribution histogram of the likelihood to vote" width="672" />
<p class="caption">
Figure 2: Probability distribution histogram of the likelihood to vote
</p>
</div>
<div id="histogram-example-2-political-knowledge" class="section level4">
<h4>Histogram Example 2: Political knowledge</h4>
<p>We are now going to move on to a few slighly more complex examples.</p>
<p>Let’s start by visualising the histogram for the ‘political knowledge’ variable (from 0 to 10), which represents the number of Australian politics quiz questions the survey respondent got right.</p>
<pre class="r"><code>barplot(table(elect_2013$pol_knowledge))</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-17"></span>
<img src="/docs/soci832_1_intro_univariate_files/figure-html/unnamed-chunk-17-1.png" alt="Histogram of political knowledge" width="672" />
<p class="caption">
Figure 3: Histogram of political knowledge
</p>
</div>
<p>We can see that there is pretty even distribution of respondents across the levels of answers, but only a very small number (around 130) got 10/10 for the quiz.</p>
<p>Imagine that for some reason we actually wanted to only have five bins, 0-1, 2-3, 4-5, etc.</p>
<p>How do we do this?</p>
<p>First we create a variable called ‘bins’, using one of two commands: either ‘seq()’ or ‘c()’</p>
<p>seq() allows us to specify the min and max, and then the width of bins. The following commands creates bins between 0 and 10, with a width of 2:</p>
<pre class="r"><code>bins &lt;- seq(0, 10, by=2)</code></pre>
<p>You could also make the bins with c(). With c() you just specify the exact bins</p>
<pre class="r"><code>bins &lt;- c(0,2,4,6,8,10)</code></pre>
<p>We then go through two steps to make a histogram based on these bins. We first use ‘cut()’ to create a new variable called ‘x’. This creates a variable, x, which the values are simply the bins (so a person who had got one quiz question right, and had a 1 for ‘political knowledge’ would have that ‘1’ replaced with the name of the ‘bin’, in this case “(0,2]”)</p>
<p>We then plot x as done previously with barplot() and table()</p>
<pre class="r"><code>x &lt;- cut(elect_2013$pol_knowledge, breaks=bins)
barplot(table(x))</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-20"></span>
<img src="/docs/soci832_1_intro_univariate_files/figure-html/unnamed-chunk-20-1.png" alt="Histogram of political knowledge using five bins" width="672" />
<p class="caption">
Figure 4: Histogram of political knowledge using five bins
</p>
</div>
</div>
<div id="histogram-example-3-age" class="section level4">
<h4>Histogram Example 3: Age</h4>
<p>We will do one quick last example with age.</p>
<p>Let’s look at the age histogram, with bins just one year wide:</p>
<pre class="r"><code>barplot(table(elect_2013$age))</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-21"></span>
<img src="/docs/soci832_1_intro_univariate_files/figure-html/unnamed-chunk-21-1.png" alt="Histogram of age" width="672" />
<p class="caption">
Figure 5: Histogram of age
</p>
</div>
<p>Let’s now look at it, with the variable divided into bins of width 5 years.</p>
<pre class="r"><code>bins &lt;- seq(0, 110, by=5)
x &lt;- cut(elect_2013$age, breaks=bins)
barplot(table(x))</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-22"></span>
<img src="/docs/soci832_1_intro_univariate_files/figure-html/unnamed-chunk-22-1.png" alt="Histogram of age with bins of 5 years" width="672" />
<p class="caption">
Figure 6: Histogram of age with bins of 5 years
</p>
</div>
<p>And as a probablity density graph:</p>
<pre class="r"><code>cases &lt;- length(elect_2013$age
            [!is.na(elect_2013$age)])
barplot(table(x)/cases)</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-23"></span>
<img src="/docs/soci832_1_intro_univariate_files/figure-html/unnamed-chunk-23-1.png" alt="Probability density histogram of age" width="672" />
<p class="caption">
Figure 7: Probability density histogram of age
</p>
</div>
<p>There is lots more you can do with ‘barplot()’. A simple extension is to give the graph colour.</p>
<pre class="r"><code>barplot(table(x)/cases, col=&quot;Red&quot;)</code></pre>
<p><img src="/docs/soci832_1_intro_univariate_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>There are also lots of more powerful and beautiful graphs that can be made in R. Later in semester Young will teach you some of these techniques. If you want to teach yourself one place to start for graphing univariate statistics with the package ggplot2 is here: <a href="http://www.sthda.com/english/articles/32-r-graphics-essentials/133-plot-one-variable-frequency-graph-density-distribution-and-more/#density-plots" class="uri">http://www.sthda.com/english/articles/32-r-graphics-essentials/133-plot-one-variable-frequency-graph-density-distribution-and-more/#density-plots</a></p>
</div>
</div>
</div>
<div id="lesson-3-univariate-statistics-with-summarytools" class="section level1">
<h1>Lesson 3: Univariate statistics with summarytools</h1>
<p>summarytools is a powerful package that allows users to quickly and easily generate tables that can be cut and pasted directly into papers, presentations, and/or codebooks.</p>
<div id="resources" class="section level3">
<h3>RESOURCES</h3>
<p>Excellent introduction by the author: <a href="https://cran.r-project.org/web/packages/summarytools/vignettes/Introduction.html" class="uri">https://cran.r-project.org/web/packages/summarytools/vignettes/Introduction.html</a></p>
<p>The full manual: <a href="https://cran.r-project.org/web/packages/summarytools/summarytools.pdf" class="uri">https://cran.r-project.org/web/packages/summarytools/summarytools.pdf</a></p>
</div>
<div id="why-use-it" class="section level3">
<h3>WHY USE IT?</h3>
<p>Because it quickly and easily generates beautiful tables that you will need for almost every paper, presentation, or codebook that you write.</p>
</div>
<div id="core-functions-freq-ctable-descr-dfsummary." class="section level3">
<h3>CORE FUNCTIONS: freq(), ctable(), descr(), dfSummary().</h3>
</div>
<div id="tips" class="section level3">
<h3>TIPS:</h3>
<ul>
<li>for beginners it is almost always easier to use html output, rather than rmarkdown;</li>
<li>when writing code, send files to browser so you can see your output immediately;</li>
<li>when you are ready to publish, you can (1) screenshot; (2) cut and paste the tables into excel or word; or (3) save as a html file, using the ‘file=’ argument in the print() function.</li>
</ul>
<pre class="r"><code>install.packages(&quot;summarytools&quot;, 
                 repos = &#39;http://cran.rstudio.com&#39;) </code></pre>
<pre><code>## Installing package into &#39;C:/Users/nickh/Documents/R/win-library/3.5&#39;
## (as &#39;lib&#39; is unspecified)</code></pre>
<pre><code>## package &#39;summarytools&#39; successfully unpacked and MD5 sums checked
## 
## The downloaded binary packages are in
##  C:\Users\nickh\AppData\Local\Temp\RtmpWWK2yE\downloaded_packages</code></pre>
<pre class="r"><code># install the package (once, and then # it out)
        library(summarytools) # load the library</code></pre>
</div>
<div id="lesson-3.1-freq-function" class="section level2">
<h2>LESSON 3.1: freq() function</h2>
<p>This function gives the count and proportions of each value of a variable. Note that it only takes a single variable as input (not a whole dataframe).</p>
<div id="dont-do-this" class="section level3">
<h3>3.1.1 Don’t do this</h3>
<p>You almost NEVER want to run ‘summarytools’ functions WITHOUT putting them inside the ‘print()’ function and sending them to the browser. To understand why, run the next line and look at the ugly output sent to the console.</p>
<pre class="r"><code>freq(elect_2013$pol_knowledge)</code></pre>
<pre><code>## Frequencies  
## elect_2013$pol_knowledge  
## Type: Numeric  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##           0    410     10.37          10.37     10.37          10.37
##           1    303      7.66          18.03      7.66          18.03
##           2    380      9.61          27.64      9.61          27.64
##           3    382      9.66          37.29      9.66          37.29
##           4    403     10.19          47.48     10.19          47.48
##           5    425     10.75          58.23     10.75          58.23
##           6    376      9.51          67.74      9.51          67.74
##           7    435     11.00          78.74     11.00          78.74
##           8    387      9.79          88.52      9.79          88.52
##           9    318      8.04          96.56      8.04          96.56
##          10    136      3.44         100.00      3.44         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total   3955    100.00         100.00    100.00         100.00</code></pre>
<p>OK, it’s not terrible, but you wouldn’t want to paste that straight into an article or presentation.</p>
</div>
<div id="basic-command" class="section level3">
<h3>3.1.2 Basic command</h3>
<p>Now let’s run the same command, but we will put it inside a print() function, and send it to browser.</p>
<pre class="r"><code>print(freq(elect_2013$pol_knowledge), 
      method = &#39;browser&#39;)</code></pre>
<p>A table should have openned in your browser (such as Chrome Safari, Internet Explorer, Firefox, or Edge) and look like the one below.</p>
<div class="container st-container">
<h3>Frequencies</h3>
<h4>elect_2013$pol_knowledge</h4>
<strong>Type</strong>: Numeric
<br/>
<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-freq-table ">
  <thead>
    <tr>
      <th colspan="2"></th>
      <th colspan="2" align="center" class="st-protect-top-border">Valid</th>
      <th colspan="2" align="center" class="st-protect-top-border">Total</th>
    </tr>
    <tr>
      <th align="center">pol_knowledge</th>
      <th align="center">Freq</th>
      <th align="center">%</th>
      <th align="center">% Cum.</th>
      <th align="center">%</th>
      <th align="center">% Cum.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th align="center" class="st-protect-top-border">0</th>
      <td align="center">410</td>
      <td align="center">10.37</td>
      <td align="center">10.37</td>
      <td align="center">10.37</td>
      <td align="center">10.37</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">1</th>
      <td align="center">303</td>
      <td align="center">7.66</td>
      <td align="center">18.03</td>
      <td align="center">7.66</td>
      <td align="center">18.03</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">2</th>
      <td align="center">380</td>
      <td align="center">9.61</td>
      <td align="center">27.64</td>
      <td align="center">9.61</td>
      <td align="center">27.64</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">3</th>
      <td align="center">382</td>
      <td align="center">9.66</td>
      <td align="center">37.29</td>
      <td align="center">9.66</td>
      <td align="center">37.29</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">4</th>
      <td align="center">403</td>
      <td align="center">10.19</td>
      <td align="center">47.48</td>
      <td align="center">10.19</td>
      <td align="center">47.48</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">5</th>
      <td align="center">425</td>
      <td align="center">10.75</td>
      <td align="center">58.23</td>
      <td align="center">10.75</td>
      <td align="center">58.23</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">6</th>
      <td align="center">376</td>
      <td align="center">9.51</td>
      <td align="center">67.74</td>
      <td align="center">9.51</td>
      <td align="center">67.74</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">7</th>
      <td align="center">435</td>
      <td align="center">11.00</td>
      <td align="center">78.74</td>
      <td align="center">11.00</td>
      <td align="center">78.74</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">8</th>
      <td align="center">387</td>
      <td align="center">9.79</td>
      <td align="center">88.52</td>
      <td align="center">9.79</td>
      <td align="center">88.52</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">9</th>
      <td align="center">318</td>
      <td align="center">8.04</td>
      <td align="center">96.56</td>
      <td align="center">8.04</td>
      <td align="center">96.56</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">10</th>
      <td align="center">136</td>
      <td align="center">3.44</td>
      <td align="center">100.00</td>
      <td align="center">3.44</td>
      <td align="center">100.00</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">&lt;NA&gt;</th>
      <td align="center">0</td>
      <td align="center"></td>
      <td align="center"></td>
      <td align="center">0.00</td>
      <td align="center">100.00</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">Total</th>
      <td align="center">3955</td>
      <td align="center">100.00</td>
      <td align="center">100.00</td>
      <td align="center">100.00</td>
      <td align="center">100.00</td>
    </tr>
  </tbody>
</table>
<p><p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.3 (<a href='https://www.r-project.org/'>R</a> version 3.5.3)<br/>2019-07-03</p></p>
</div>
<p>Notice how it has a much more attractive layout.</p>
</div>
<div id="settings" class="section level3">
<h3>3.1.3 Settings</h3>
<p>There are a few different settings we can use to make this table prettier.</p>
<p>We can omit the headings</p>
<pre class="r"><code>print(freq(elect_2013$pol_knowledge,
      omit.headings = TRUE), 
      method = &#39;browser&#39;)</code></pre>
<pre><code>## &#39;omit.headings&#39; argument has been replaced by &#39;headings&#39;; setting headings = FALSE</code></pre>
<div class="container st-container">
<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-freq-table ">
  <thead>
    <tr>
      <th colspan="2"></th>
      <th colspan="2" align="center" class="st-protect-top-border">Valid</th>
      <th colspan="2" align="center" class="st-protect-top-border">Total</th>
    </tr>
    <tr>
      <th align="center">pol_knowledge</th>
      <th align="center">Freq</th>
      <th align="center">%</th>
      <th align="center">% Cum.</th>
      <th align="center">%</th>
      <th align="center">% Cum.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th align="center" class="st-protect-top-border">0</th>
      <td align="center">410</td>
      <td align="center">10.37</td>
      <td align="center">10.37</td>
      <td align="center">10.37</td>
      <td align="center">10.37</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">1</th>
      <td align="center">303</td>
      <td align="center">7.66</td>
      <td align="center">18.03</td>
      <td align="center">7.66</td>
      <td align="center">18.03</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">2</th>
      <td align="center">380</td>
      <td align="center">9.61</td>
      <td align="center">27.64</td>
      <td align="center">9.61</td>
      <td align="center">27.64</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">3</th>
      <td align="center">382</td>
      <td align="center">9.66</td>
      <td align="center">37.29</td>
      <td align="center">9.66</td>
      <td align="center">37.29</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">4</th>
      <td align="center">403</td>
      <td align="center">10.19</td>
      <td align="center">47.48</td>
      <td align="center">10.19</td>
      <td align="center">47.48</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">5</th>
      <td align="center">425</td>
      <td align="center">10.75</td>
      <td align="center">58.23</td>
      <td align="center">10.75</td>
      <td align="center">58.23</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">6</th>
      <td align="center">376</td>
      <td align="center">9.51</td>
      <td align="center">67.74</td>
      <td align="center">9.51</td>
      <td align="center">67.74</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">7</th>
      <td align="center">435</td>
      <td align="center">11.00</td>
      <td align="center">78.74</td>
      <td align="center">11.00</td>
      <td align="center">78.74</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">8</th>
      <td align="center">387</td>
      <td align="center">9.79</td>
      <td align="center">88.52</td>
      <td align="center">9.79</td>
      <td align="center">88.52</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">9</th>
      <td align="center">318</td>
      <td align="center">8.04</td>
      <td align="center">96.56</td>
      <td align="center">8.04</td>
      <td align="center">96.56</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">10</th>
      <td align="center">136</td>
      <td align="center">3.44</td>
      <td align="center">100.00</td>
      <td align="center">3.44</td>
      <td align="center">100.00</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">&lt;NA&gt;</th>
      <td align="center">0</td>
      <td align="center"></td>
      <td align="center"></td>
      <td align="center">0.00</td>
      <td align="center">100.00</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">Total</th>
      <td align="center">3955</td>
      <td align="center">100.00</td>
      <td align="center">100.00</td>
      <td align="center">100.00</td>
      <td align="center">100.00</td>
    </tr>
  </tbody>
</table>
<p><p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.3 (<a href='https://www.r-project.org/'>R</a> version 3.5.3)<br/>2019-07-03</p></p>
</div>
<p>We can omit the totals</p>
<pre class="r"><code>print(freq(elect_2013$pol_knowledge, 
        totals = FALSE), 
        method = &#39;browser&#39;)</code></pre>
<p>We can omit the reporting of NAs (missing)</p>
<pre class="r"><code>print(freq(elect_2013$pol_knowledge, 
       report.nas = FALSE), 
       method = &#39;browser&#39;)</code></pre>
<p>We can remove the footnote</p>
<pre class="r"><code>print(freq(elect_2013$pol_knowledge, 
       report.nas = FALSE), 
       method = &#39;browser&#39;, footnote = NA)</code></pre>
</div>
<div id="putting-it-all-together" class="section level3">
<h3>3.1.4. Putting it all together</h3>
<p>And we can put all that together</p>
<pre class="r"><code>print(freq(elect_2013$pol_knowledge, 
       omit.headings = TRUE, 
       totals = FALSE, 
       report.nas = FALSE), 
       method = &#39;browser&#39;, footnote = NA)</code></pre>
<pre><code>## &#39;omit.headings&#39; argument has been replaced by &#39;headings&#39;; setting headings = FALSE</code></pre>
<div class="container st-container"><table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-freq-table-nomiss ">
  <thead>
    <tr>
      <th align="center" class="st-protect-top-border">pol_knowledge</th>
      <th align="center" class="st-protect-top-border">Freq</th>
      <th align="center" class="st-protect-top-border">%</th>
      <th align="center" class="st-protect-top-border">% Cum.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th align="center" class="st-protect-top-border">0</th>
      <td align="center">410</td>
      <td align="center">10.37</td>
      <td align="center">10.37</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">1</th>
      <td align="center">303</td>
      <td align="center">7.66</td>
      <td align="center">18.03</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">2</th>
      <td align="center">380</td>
      <td align="center">9.61</td>
      <td align="center">27.64</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">3</th>
      <td align="center">382</td>
      <td align="center">9.66</td>
      <td align="center">37.29</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">4</th>
      <td align="center">403</td>
      <td align="center">10.19</td>
      <td align="center">47.48</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">5</th>
      <td align="center">425</td>
      <td align="center">10.75</td>
      <td align="center">58.23</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">6</th>
      <td align="center">376</td>
      <td align="center">9.51</td>
      <td align="center">67.74</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">7</th>
      <td align="center">435</td>
      <td align="center">11.00</td>
      <td align="center">78.74</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">8</th>
      <td align="center">387</td>
      <td align="center">9.79</td>
      <td align="center">88.52</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">9</th>
      <td align="center">318</td>
      <td align="center">8.04</td>
      <td align="center">96.56</td>
    </tr>
    <tr>
      <th align="center" class="st-protect-top-border">10</th>
      <td align="center">136</td>
      <td align="center">3.44</td>
      <td align="center">100.00</td>
    </tr>
  </tbody>
</table></div>
</div>
<div id="save-to-file" class="section level3">
<h3>3.1.5. Save to file</h3>
<p>If we want to save this to a file, then we use the same command, but replace the ‘method =’ argument with a ‘file =’ argument, as below:</p>
<pre class="r"><code>print(freq(elect_2013$pol_knowledge, 
       omit.headings = TRUE, 
       totals = FALSE, 
       report.nas = FALSE), 
       file = &quot;pol_know_freq.html&quot;, footnote = NA)</code></pre>
<pre><code>## &#39;omit.headings&#39; argument has been replaced by &#39;headings&#39;; setting headings = FALSE</code></pre>
<pre><code>## Switching method to &#39;browser&#39;</code></pre>
<pre><code>## Output file written: C:\Users\nickh\methods101\content\docs\pol_know_freq.html</code></pre>
<p>and if you go to your default folder (set at the beginning of this session), then you will find the file ‘pol_know_freq.html’. If you double click on it then it will open in a browser.</p>
</div>
</div>
<div id="lesson-3.2-descr-function" class="section level2">
<h2>Lesson 3.2: descr() function</h2>
<p>This function calculates a wide range basic univariate statistics such as mean, standard deviation, min, max, skewness, etc. This function can calcuate these on all variables in a dataset meaning it can be used to summarise an entire dataset very quickly. This command is great for doing a descriptive statistics table - a table which is expected in almost all academic papers.</p>
<p>This is the simplest form of the command</p>
<pre class="r"><code>print(descr(elect_2013$pol_knowledge), 
      method = &quot;browser&quot;)</code></pre>
<div class="container st-container">
<h3>Descriptive Statistics</h3>
<h4>elect_2013$pol_knowledge</h4>
<strong>N</strong>: 3955
<br/>
<table class="table table-bordered table-striped st-table st-table-bordered st-table-striped st-descr-table ">
  <thead>
    <tr>
      <th></th>
      <th align="center" class="st-protect-top-border">pol_<br/>knowledge</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong>Mean</strong></td>
      <td><span>4.69</span></td>
    </tr>
    <tr>
      <td>
        <strong>Std.Dev</strong></td>
      <td><span>2.94</span></td>
    </tr>
    <tr>
      <td>
        <strong>Min</strong></td>
      <td><span>0.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>Q1</strong></td>
      <td><span>2.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>Median</strong></td>
      <td><span>5.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>Q3</strong></td>
      <td><span>7.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>Max</strong></td>
      <td><span>10.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>MAD</strong></td>
      <td><span>2.97</span></td>
    </tr>
    <tr>
      <td>
        <strong>IQR</strong></td>
      <td><span>5.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>CV</strong></td>
      <td><span>0.63</span></td>
    </tr>
    <tr>
      <td>
        <strong>Skewness</strong></td>
      <td><span>-0.01</span></td>
    </tr>
    <tr>
      <td>
        <strong>SE.Skewness</strong></td>
      <td><span>0.04</span></td>
    </tr>
    <tr>
      <td>
        <strong>Kurtosis</strong></td>
      <td><span>-1.12</span></td>
    </tr>
    <tr>
      <td>
        <strong>N.Valid</strong></td>
      <td><span>3955</span></td>
    </tr>
    <tr>
      <td>
        <strong>Pct.Valid</strong></td>
      <td><span>100.00</span></td>
    </tr>
  </tbody>
</table>
<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.3 (<a href='https://www.r-project.org/'>R</a> version 3.5.3)<br/>2019-07-03</p>
</div>
<p>However, when reporting variables, we often like them to be presented as the rows, not columns. To change this we used the argument ‘transpose’</p>
<pre class="r"><code>print(descr(elect_2013$pol_knowledge, transpose = TRUE),
      method = &quot;browser&quot;)</code></pre>
<div class="container st-container">
<h3>Descriptive Statistics</h3>
<h4>elect_2013$pol_knowledge</h4>
<strong>N</strong>: 3955
<br/>
<table class="table table-bordered table-striped st-table st-table-bordered st-table-striped st-descr-table ">
  <thead>
    <tr>
      <th></th>
      <th align="center" class="st-protect-top-border">Mean</th>
      <th align="center" class="st-protect-top-border">Std.Dev</th>
      <th align="center" class="st-protect-top-border">Min</th>
      <th align="center" class="st-protect-top-border">Q1</th>
      <th align="center" class="st-protect-top-border">Median</th>
      <th align="center" class="st-protect-top-border">Q3</th>
      <th align="center" class="st-protect-top-border">Max</th>
      <th align="center" class="st-protect-top-border">MAD</th>
      <th align="center" class="st-protect-top-border">IQR</th>
      <th align="center" class="st-protect-top-border">CV</th>
      <th align="center" class="st-protect-top-border">Skewness</th>
      <th align="center" class="st-protect-top-border">SE.Skewness</th>
      <th align="center" class="st-protect-top-border">Kurtosis</th>
      <th align="center" class="st-protect-top-border">N.Valid</th>
      <th align="center" class="st-protect-top-border">Pct.Valid</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong>pol_knowledge</strong></td>
      <td><span>4.69</span></td>
      <td><span>2.94</span></td>
      <td><span>0.00</span></td>
      <td><span>2.00</span></td>
      <td><span>5.00</span></td>
      <td><span>7.00</span></td>
      <td><span>10.00</span></td>
      <td><span>2.97</span></td>
      <td><span>5.00</span></td>
      <td><span>0.63</span></td>
      <td><span>-0.01</span></td>
      <td><span>0.04</span></td>
      <td><span>-1.12</span></td>
      <td><span>3955</span></td>
      <td><span>100.00</span></td>
    </tr>
  </tbody>
</table>
<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.3 (<a href='https://www.r-project.org/'>R</a> version 3.5.3)<br/>2019-07-03</p>
</div>
<p>Generally we don’t want all these statistics, so we can limit the statistics reported with the argument ‘stats’.</p>
<p>Note: I’ve also removed the headings and footnote.</p>
<pre class="r"><code>print(descr(elect_2013$pol_knowledge, 
      omit.headings = TRUE,
      stats = c(&quot;mean&quot;, &quot;sd&quot;, &quot;min&quot;, &quot;max&quot;), 
      transpose = TRUE),
      method = &quot;browser&quot;,
      footnote = NA)</code></pre>
<pre><code>## &#39;omit.headings&#39; argument has been replaced by &#39;headings&#39;; setting headings = FALSE</code></pre>
<div class="container st-container"><table class="table table-bordered table-striped st-table st-table-bordered st-table-striped st-descr-table ">
  <thead>
    <tr>
      <th></th>
      <th align="center" class="st-protect-top-border">Mean</th>
      <th align="center" class="st-protect-top-border">Std.Dev</th>
      <th align="center" class="st-protect-top-border">Min</th>
      <th align="center" class="st-protect-top-border">Max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong>pol_knowledge</strong></td>
      <td><span>4.69</span></td>
      <td><span>2.94</span></td>
      <td><span>0.00</span></td>
      <td><span>10.00</span></td>
    </tr>
  </tbody>
</table></div>
<p>Note that when using the stats argument, we put the names of the stats we want using the “c()” function. If you want to know the commands for each of the different stats, then look at the help file (type ?descr)</p>
<p>However, remember that the data from the Australian Electoral Study needs to be weighted to account for the difference between the sample and the population. We can do this with the argument ‘weights’</p>
<pre class="r"><code>print(descr(elect_2013$pol_knowledge, 
      omit.headings = TRUE,
      stats = c(&quot;mean&quot;, &quot;sd&quot;, &quot;min&quot;, &quot;max&quot;), 
      transpose = TRUE,
      weights = elect_2013$weight),
      method = &quot;browser&quot;, 
      footnote = NA)</code></pre>
<pre><code>## &#39;omit.headings&#39; argument has been replaced by &#39;headings&#39;; setting headings = FALSE</code></pre>
<div class="container st-container"><table class="table table-bordered table-striped st-table st-table-bordered st-table-striped st-descr-table ">
  <thead>
    <tr>
      <th></th>
      <th align="center" class="st-protect-top-border">Mean</th>
      <th align="center" class="st-protect-top-border">Std.Dev</th>
      <th align="center" class="st-protect-top-border">Min</th>
      <th align="center" class="st-protect-top-border">Max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong>pol_knowledge</strong></td>
      <td><span>4.41</span></td>
      <td><span>2.94</span></td>
      <td><span>0.00</span></td>
      <td><span>10.00</span></td>
    </tr>
  </tbody>
</table></div>
<p>The real power of descr() is that it can calculate these statistics for all variables in a dataset. We can do this by just calling descr() on the data frame.</p>
<p><strong>Note:</strong> In this case, I’ve limited the output to this webpage to the first 10 variables, so that it doesn’t take up too much space.</p>
<pre class="r"><code>print(descr(elect_2013, 
      omit.headings = TRUE, 
      stats = c(&quot;mean&quot;, &quot;sd&quot;, &quot;min&quot;, &quot;max&quot;),
      transpose = TRUE, 
      weights = elect_2013$weight), 
      method = &quot;browser&quot;, footnote = NA)</code></pre>
<pre><code>## &#39;omit.headings&#39; argument has been replaced by &#39;headings&#39;; setting headings = FALSE</code></pre>
<div class="container st-container"><table class="table table-bordered table-striped st-table st-table-bordered st-table-striped st-descr-table ">
  <thead>
    <tr>
      <th></th>
      <th align="center" class="st-protect-top-border">Mean</th>
      <th align="center" class="st-protect-top-border">Std.Dev</th>
      <th align="center" class="st-protect-top-border">Min</th>
      <th align="center" class="st-protect-top-border">Max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong>pol_knowledge</strong></td>
      <td><span>4.41</span></td>
      <td><span>2.94</span></td>
      <td><span>0.00</span></td>
      <td><span>10.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>likelihood_vote</strong></td>
      <td><span>4.20</span></td>
      <td><span>1.20</span></td>
      <td><span>1.00</span></td>
      <td><span>5.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>know1</strong></td>
      <td><span>1.51</span></td>
      <td><span>0.86</span></td>
      <td><span>1.00</span></td>
      <td><span>3.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>know2</strong></td>
      <td><span>1.96</span></td>
      <td><span>0.94</span></td>
      <td><span>1.00</span></td>
      <td><span>3.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>know3</strong></td>
      <td><span>2.08</span></td>
      <td><span>0.81</span></td>
      <td><span>1.00</span></td>
      <td><span>3.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>know4</strong></td>
      <td><span>2.21</span></td>
      <td><span>0.79</span></td>
      <td><span>1.00</span></td>
      <td><span>3.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>know5</strong></td>
      <td><span>1.69</span></td>
      <td><span>0.79</span></td>
      <td><span>1.00</span></td>
      <td><span>3.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>know6</strong></td>
      <td><span>2.17</span></td>
      <td><span>0.75</span></td>
      <td><span>1.00</span></td>
      <td><span>3.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>know7</strong></td>
      <td><span>3.60</span></td>
      <td><span>1.16</span></td>
      <td><span>1.00</span></td>
      <td><span>5.00</span></td>
    </tr>
    <tr>
      <td>
        <strong>know8</strong></td>
      <td><span>2.94</span></td>
      <td><span>1.40</span></td>
      <td><span>1.00</span></td>
      <td><span>5.00</span></td>
    </tr>
  </tbody>
</table></div>
</div>
<div id="lesson-3.3-dfsummary-function" class="section level2">
<h2>Lesson 3.3: dfSummary() function</h2>
<p>While the ‘descr()’ function is good for making publication quality tables, the dfSummary() function is more for the private use of the data analyst. dfSummary() is the kind of function you use to ‘get a quick feel’ for your data. It lets you quickly see the number of missing values and a rough histogram of the values and also see the percent of cases of each value. This can be very useful when you are trying to assess the quality of data, or looking for interesting patterns you may want to explore later.</p>
<p>The following command gives a summary of just one variable:</p>
<pre class="r"><code>print(dfSummary(elect_2013$pol_knowledge), 
      method=&quot;browser&quot;)</code></pre>
<pre><code>## elect_2013$pol_knowledge was converted to a data frame</code></pre>
<div class="container st-container">
<h3>Data Frame Summary</h3>
<h4>elect_2013</h4>
<strong>Dimensions</strong>: 3955 x 1
  <br/><strong>Duplicates</strong>: 3944
<br/>
<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline ">
  <thead>
    <tr>
      <th align="center" class="no st-protect-top-border"><strong>No</strong></th>
      <th align="center" class="variable st-protect-top-border"><strong>Variable</strong></th>
      <th align="center" class="stats.values st-protect-top-border"><strong>Stats / Values</strong></th>
      <th align="center" class="freqs.pct.valid st-protect-top-border"><strong>Freqs (% of Valid)</strong></th>
      <th align="center" class="graph st-protect-top-border"><strong>Graph</strong></th>
      <th align="center" class="valid st-protect-top-border"><strong>Valid</strong></th>
      <th align="center" class="missing st-protect-top-border"><strong>Missing</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center">1</td>
      <td align="left">pol_knowledge
[numeric]</td>
      <td align="left">Mean (sd) : 4.7 (2.9)
min < med < max:
0 < 5 < 10
IQR (CV) : 5 (0.6)</td>
      <td align="left" style="vertical-align:middle">11 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqby8vL///8shn5hAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH4wcEBwk56s6tDwAAAI5JREFUaN7t1s0JgDAMQOGuoBvYbmD3302wEQy0PSTx5/DeJSD6EUHRlMhSbm2LK8FKPQMDAwMDAwMDAwMD+w5b5Sc/Bmsn7lZM7eLFyv3yf2ByfzGYHHwe6z4hGsuqGdZdUGOTce0Sg9XeAAMbYPpFcGJ6QTAwMDAwMLC3Mfmwx2AywMDAwMDGWA4pkaUDCdHQuzc6OnsAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTktMDctMDNUMjE6MDk6NTcrMTA6MDDHLg0OAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE5LTA3LTAzVDIxOjA5OjU3KzEwOjAwtnO1sgAAAABJRU5ErkJggg=="></td>
      <td align="center">3955
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
  </tbody>
</table>
<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.3 (<a href='https://www.r-project.org/'>R</a> version 3.5.3)<br/>2019-07-03</p>
</div>
<p>The next command gives a summary of the entire dataset. For display purposes, I’ve just shown the first five variables:</p>
<pre class="r"><code>print(dfSummary(elect_2013), 
      method=&#39;browser&#39;)</code></pre>
<div class="container st-container">
<h3>Data Frame Summary</h3>
<h4>elect_2013</h4>
<strong>Dimensions</strong>: 3955 x 5
  <br/><strong>Duplicates</strong>: 3397
<br/>
<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline ">
  <thead>
    <tr>
      <th align="center" class="no st-protect-top-border"><strong>No</strong></th>
      <th align="center" class="variable st-protect-top-border"><strong>Variable</strong></th>
      <th align="center" class="stats.values st-protect-top-border"><strong>Stats / Values</strong></th>
      <th align="center" class="freqs.pct.valid st-protect-top-border"><strong>Freqs (% of Valid)</strong></th>
      <th align="center" class="graph st-protect-top-border"><strong>Graph</strong></th>
      <th align="center" class="valid st-protect-top-border"><strong>Valid</strong></th>
      <th align="center" class="missing st-protect-top-border"><strong>Missing</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center">1</td>
      <td align="left">pol_knowledge
[numeric]</td>
      <td align="left">Mean (sd) : 4.7 (2.9)
min < med < max:
0 < 5 < 10
IQR (CV) : 5 (0.6)</td>
      <td align="left" style="vertical-align:middle">11 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqby8vL///8shn5hAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH4wcEBwk6c8f8tQAAAI5JREFUaN7t1s0JgDAMQOGuoBvYbmD3302wEQy0PSTx5/DeJSD6EUHRlMhSbm2LK8FKPQMDAwMDAwMDAwMD+w5b5Sc/Bmsn7lZM7eLFyv3yf2ByfzGYHHwe6z4hGsuqGdZdUGOTce0Sg9XeAAMbYPpFcGJ6QTAwMDAwMLC3Mfmwx2AywMDAwMDGWA4pkaUDCdHQuzc6OnsAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTktMDctMDNUMjE6MDk6NTgrMTA6MDAxZn3nAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE5LTA3LTAzVDIxOjA5OjU4KzEwOjAwQDvFWwAAAABJRU5ErkJggg=="></td>
      <td align="center">3955
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">2</td>
      <td align="left">likelihood_vote
[numeric]</td>
      <td align="left">Mean (sd) : 4.4 (1.1)
min < med < max:
1 < 5 < 5
IQR (CV) : 1 (0.2)</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">1</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">126</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">3.2%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">2</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">269</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">6.8%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">3</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">236</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">6.0%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">4</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">721</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">18.4%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">5</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">2574</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">65.6%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG8AAACABAMAAAD3+SoEAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH4wcEBwk6c8f8tQAAAIJJREFUWMPt1cENgCAQRFFK0A506UD6700heiDxwCyJGP3/7Du4hyGEf2Rms9R0wpg2IBAIVKF7czQ1FFpudcCYjoBAIPAh6B4rgYyG5R89MF9VeuiAQCCwA7rHSjGDoVUJsDxzVy3nBQKBwA7oHquGT98CTW25u2pLQCAQ2LE5X28HpgZXfLRpNrAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTktMDctMDNUMjE6MDk6NTgrMTA6MDAxZn3nAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE5LTA3LTAzVDIxOjA5OjU4KzEwOjAwQDvFWwAAAABJRU5ErkJggg=="></td>
      <td align="center">3926
(99.27%)</td>
      <td align="center">29
(0.73%)</td>
    </tr>
    <tr>
      <td align="center">3</td>
      <td align="left">know1
[numeric]</td>
      <td align="left">Mean (sd) : 1.5 (0.8)
min < med < max:
1 < 1 < 3
IQR (CV) : 1 (0.6)</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">1</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">2827</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">74.4%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">2</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">105</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">2.8%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">3</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">866</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">22.8%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABQBAMAAAApXgzAAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH4wcEBwk6c8f8tQAAAFVJREFUWMPt1rENACAIBVFXcARhA91/Nxs7KiExBu76135orXbi7HBdriYcDoc/5cGt684ycJER4brgcDg8Pw9Opcsm4ebyjitu3gM4HA7/kQe3rmob4XjSScL4ECwAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTktMDctMDNUMjE6MDk6NTgrMTA6MDAxZn3nAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE5LTA3LTAzVDIxOjA5OjU4KzEwOjAwQDvFWwAAAABJRU5ErkJggg=="></td>
      <td align="center">3798
(96.03%)</td>
      <td align="center">157
(3.97%)</td>
    </tr>
    <tr>
      <td align="center">4</td>
      <td align="left">know2
[numeric]</td>
      <td align="left">Mean (sd) : 1.9 (0.9)
min < med < max:
1 < 2 < 3
IQR (CV) : 2 (0.5)</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">1</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">1805</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">48.0%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">2</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">446</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">11.9%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">3</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">1506</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">40.1%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFUAAABQBAMAAACaFiTaAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH4wcEBwk6c8f8tQAAAFZJREFUSMft1LsJACAMRVFH0A38jOD+u9mIlZqkECLcW5/GwDOE/6qK8rSty2Gx2LO17C0pio7sekCR7boZFot9bi3bTIo82ftvWvY324bFYiVr2dtPDYuZeXol1Wn+AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE5LTA3LTAzVDIxOjA5OjU4KzEwOjAwMWZ95wAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxOS0wNy0wM1QyMTowOTo1OCsxMDowMEA7xVsAAAAASUVORK5CYII="></td>
      <td align="center">3757
(94.99%)</td>
      <td align="center">198
(5.01%)</td>
    </tr>
    <tr>
      <td align="center">5</td>
      <td align="left">know3
[numeric]</td>
      <td align="left">Mean (sd) : 2 (0.8)
min < med < max:
1 < 2 < 3
IQR (CV) : 2 (0.4)</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">1</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">1155</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">30.6%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">2</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">1334</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">35.4%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">3</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">1284</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">34.0%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEIAAABQBAMAAABfZL5LAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH4wcEBwk6c8f8tQAAAExJREFUSMdjYBg8QAk7UBQUFISqUDbGCkZVjKqgowrC6VQQN6CrCiXcAL9vgcBoVMWoikGjgnBKHvx5TpCQb41GVYyqoJcKwul0MAAAwqNMJ4IfvvAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTktMDctMDNUMjE6MDk6NTgrMTA6MDAxZn3nAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE5LTA3LTAzVDIxOjA5OjU4KzEwOjAwQDvFWwAAAABJRU5ErkJggg=="></td>
      <td align="center">3773
(95.4%)</td>
      <td align="center">182
(4.6%)</td>
    </tr>
  </tbody>
</table>
<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.3 (<a href='https://www.r-project.org/'>R</a> version 3.5.3)<br/>2019-07-03</p>
</div>
<p>**This is the end of the Univariate statistics R code/ R-script file. The class continues in the code “Week 2, Part 2, Bivariate statistics.R’**</p>
</div>
</div>
